/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestRouteImport } from './routes/test'
import { Route as SelectedWorksRouteImport } from './routes/selected-works'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkWorkIdRouteImport } from './routes/work.$workId'
import { Route as BlogArticleIdRouteImport } from './routes/blog.$articleId'

const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectedWorksRoute = SelectedWorksRouteImport.update({
  id: '/selected-works',
  path: '/selected-works',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkWorkIdRoute = WorkWorkIdRouteImport.update({
  id: '/work/$workId',
  path: '/work/$workId',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogArticleIdRoute = BlogArticleIdRouteImport.update({
  id: '/$articleId',
  path: '/$articleId',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/blog': typeof BlogRouteWithChildren
  '/careers': typeof CareersRoute
  '/selected-works': typeof SelectedWorksRoute
  '/test': typeof TestRoute
  '/blog/$articleId': typeof BlogArticleIdRoute
  '/work/$workId': typeof WorkWorkIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/blog': typeof BlogRouteWithChildren
  '/careers': typeof CareersRoute
  '/selected-works': typeof SelectedWorksRoute
  '/test': typeof TestRoute
  '/blog/$articleId': typeof BlogArticleIdRoute
  '/work/$workId': typeof WorkWorkIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/blog': typeof BlogRouteWithChildren
  '/careers': typeof CareersRoute
  '/selected-works': typeof SelectedWorksRoute
  '/test': typeof TestRoute
  '/blog/$articleId': typeof BlogArticleIdRoute
  '/work/$workId': typeof WorkWorkIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-us'
    | '/blog'
    | '/careers'
    | '/selected-works'
    | '/test'
    | '/blog/$articleId'
    | '/work/$workId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-us'
    | '/blog'
    | '/careers'
    | '/selected-works'
    | '/test'
    | '/blog/$articleId'
    | '/work/$workId'
  id:
    | '__root__'
    | '/'
    | '/about-us'
    | '/blog'
    | '/careers'
    | '/selected-works'
    | '/test'
    | '/blog/$articleId'
    | '/work/$workId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutUsRoute: typeof AboutUsRoute
  BlogRoute: typeof BlogRouteWithChildren
  CareersRoute: typeof CareersRoute
  SelectedWorksRoute: typeof SelectedWorksRoute
  TestRoute: typeof TestRoute
  WorkWorkIdRoute: typeof WorkWorkIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/selected-works': {
      id: '/selected-works'
      path: '/selected-works'
      fullPath: '/selected-works'
      preLoaderRoute: typeof SelectedWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/$workId': {
      id: '/work/$workId'
      path: '/work/$workId'
      fullPath: '/work/$workId'
      preLoaderRoute: typeof WorkWorkIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$articleId': {
      id: '/blog/$articleId'
      path: '/$articleId'
      fullPath: '/blog/$articleId'
      preLoaderRoute: typeof BlogArticleIdRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogArticleIdRoute: typeof BlogArticleIdRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogArticleIdRoute: BlogArticleIdRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutUsRoute: AboutUsRoute,
  BlogRoute: BlogRouteWithChildren,
  CareersRoute: CareersRoute,
  SelectedWorksRoute: SelectedWorksRoute,
  TestRoute: TestRoute,
  WorkWorkIdRoute: WorkWorkIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
