/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SampleRouteImport } from './routes/sample'
import { Route as OurServicesRouteImport } from './routes/our-services'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorksIndexRouteImport } from './routes/works/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as WorksWorkIdRouteImport } from './routes/works/$workId'
import { Route as BlogArticleIdRouteImport } from './routes/blog/$articleId'

const SampleRoute = SampleRouteImport.update({
  id: '/sample',
  path: '/sample',
  getParentRoute: () => rootRouteImport,
} as any)
const OurServicesRoute = OurServicesRouteImport.update({
  id: '/our-services',
  path: '/our-services',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorksIndexRoute = WorksIndexRouteImport.update({
  id: '/works/',
  path: '/works/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorksWorkIdRoute = WorksWorkIdRouteImport.update({
  id: '/works/$workId',
  path: '/works/$workId',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogArticleIdRoute = BlogArticleIdRouteImport.update({
  id: '/blog/$articleId',
  path: '/blog/$articleId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/booking': typeof BookingRoute
  '/careers': typeof CareersRoute
  '/our-services': typeof OurServicesRoute
  '/sample': typeof SampleRoute
  '/blog/$articleId': typeof BlogArticleIdRoute
  '/works/$workId': typeof WorksWorkIdRoute
  '/blog': typeof BlogIndexRoute
  '/works': typeof WorksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/booking': typeof BookingRoute
  '/careers': typeof CareersRoute
  '/our-services': typeof OurServicesRoute
  '/sample': typeof SampleRoute
  '/blog/$articleId': typeof BlogArticleIdRoute
  '/works/$workId': typeof WorksWorkIdRoute
  '/blog': typeof BlogIndexRoute
  '/works': typeof WorksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/booking': typeof BookingRoute
  '/careers': typeof CareersRoute
  '/our-services': typeof OurServicesRoute
  '/sample': typeof SampleRoute
  '/blog/$articleId': typeof BlogArticleIdRoute
  '/works/$workId': typeof WorksWorkIdRoute
  '/blog/': typeof BlogIndexRoute
  '/works/': typeof WorksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-us'
    | '/booking'
    | '/careers'
    | '/our-services'
    | '/sample'
    | '/blog/$articleId'
    | '/works/$workId'
    | '/blog'
    | '/works'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-us'
    | '/booking'
    | '/careers'
    | '/our-services'
    | '/sample'
    | '/blog/$articleId'
    | '/works/$workId'
    | '/blog'
    | '/works'
  id:
    | '__root__'
    | '/'
    | '/about-us'
    | '/booking'
    | '/careers'
    | '/our-services'
    | '/sample'
    | '/blog/$articleId'
    | '/works/$workId'
    | '/blog/'
    | '/works/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutUsRoute: typeof AboutUsRoute
  BookingRoute: typeof BookingRoute
  CareersRoute: typeof CareersRoute
  OurServicesRoute: typeof OurServicesRoute
  SampleRoute: typeof SampleRoute
  BlogArticleIdRoute: typeof BlogArticleIdRoute
  WorksWorkIdRoute: typeof WorksWorkIdRoute
  BlogIndexRoute: typeof BlogIndexRoute
  WorksIndexRoute: typeof WorksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sample': {
      id: '/sample'
      path: '/sample'
      fullPath: '/sample'
      preLoaderRoute: typeof SampleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-services': {
      id: '/our-services'
      path: '/our-services'
      fullPath: '/our-services'
      preLoaderRoute: typeof OurServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/works/': {
      id: '/works/'
      path: '/works'
      fullPath: '/works'
      preLoaderRoute: typeof WorksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/works/$workId': {
      id: '/works/$workId'
      path: '/works/$workId'
      fullPath: '/works/$workId'
      preLoaderRoute: typeof WorksWorkIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$articleId': {
      id: '/blog/$articleId'
      path: '/blog/$articleId'
      fullPath: '/blog/$articleId'
      preLoaderRoute: typeof BlogArticleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutUsRoute: AboutUsRoute,
  BookingRoute: BookingRoute,
  CareersRoute: CareersRoute,
  OurServicesRoute: OurServicesRoute,
  SampleRoute: SampleRoute,
  BlogArticleIdRoute: BlogArticleIdRoute,
  WorksWorkIdRoute: WorksWorkIdRoute,
  BlogIndexRoute: BlogIndexRoute,
  WorksIndexRoute: WorksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
