/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SampleRouteImport } from './routes/sample'
import { Route as ProcessRouteImport } from './routes/process'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkIndexRouteImport } from './routes/work/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as WorkWorkIdRouteImport } from './routes/work/$workId'
import { Route as BlogArticleIdRouteImport } from './routes/blog/$articleId'

const SampleRoute = SampleRouteImport.update({
  id: '/sample',
  path: '/sample',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessRoute = ProcessRouteImport.update({
  id: '/process',
  path: '/process',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkIndexRoute = WorkIndexRouteImport.update({
  id: '/work/',
  path: '/work/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkWorkIdRoute = WorkWorkIdRouteImport.update({
  id: '/work/$workId',
  path: '/work/$workId',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogArticleIdRoute = BlogArticleIdRouteImport.update({
  id: '/blog/$articleId',
  path: '/blog/$articleId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/careers': typeof CareersRoute
  '/process': typeof ProcessRoute
  '/sample': typeof SampleRoute
  '/blog/$articleId': typeof BlogArticleIdRoute
  '/work/$workId': typeof WorkWorkIdRoute
  '/blog': typeof BlogIndexRoute
  '/work': typeof WorkIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/careers': typeof CareersRoute
  '/process': typeof ProcessRoute
  '/sample': typeof SampleRoute
  '/blog/$articleId': typeof BlogArticleIdRoute
  '/work/$workId': typeof WorkWorkIdRoute
  '/blog': typeof BlogIndexRoute
  '/work': typeof WorkIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/careers': typeof CareersRoute
  '/process': typeof ProcessRoute
  '/sample': typeof SampleRoute
  '/blog/$articleId': typeof BlogArticleIdRoute
  '/work/$workId': typeof WorkWorkIdRoute
  '/blog/': typeof BlogIndexRoute
  '/work/': typeof WorkIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-us'
    | '/careers'
    | '/process'
    | '/sample'
    | '/blog/$articleId'
    | '/work/$workId'
    | '/blog'
    | '/work'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-us'
    | '/careers'
    | '/process'
    | '/sample'
    | '/blog/$articleId'
    | '/work/$workId'
    | '/blog'
    | '/work'
  id:
    | '__root__'
    | '/'
    | '/about-us'
    | '/careers'
    | '/process'
    | '/sample'
    | '/blog/$articleId'
    | '/work/$workId'
    | '/blog/'
    | '/work/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutUsRoute: typeof AboutUsRoute
  CareersRoute: typeof CareersRoute
  ProcessRoute: typeof ProcessRoute
  SampleRoute: typeof SampleRoute
  BlogArticleIdRoute: typeof BlogArticleIdRoute
  WorkWorkIdRoute: typeof WorkWorkIdRoute
  BlogIndexRoute: typeof BlogIndexRoute
  WorkIndexRoute: typeof WorkIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sample': {
      id: '/sample'
      path: '/sample'
      fullPath: '/sample'
      preLoaderRoute: typeof SampleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/process': {
      id: '/process'
      path: '/process'
      fullPath: '/process'
      preLoaderRoute: typeof ProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/': {
      id: '/work/'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/$workId': {
      id: '/work/$workId'
      path: '/work/$workId'
      fullPath: '/work/$workId'
      preLoaderRoute: typeof WorkWorkIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$articleId': {
      id: '/blog/$articleId'
      path: '/blog/$articleId'
      fullPath: '/blog/$articleId'
      preLoaderRoute: typeof BlogArticleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutUsRoute: AboutUsRoute,
  CareersRoute: CareersRoute,
  ProcessRoute: ProcessRoute,
  SampleRoute: SampleRoute,
  BlogArticleIdRoute: BlogArticleIdRoute,
  WorkWorkIdRoute: WorkWorkIdRoute,
  BlogIndexRoute: BlogIndexRoute,
  WorkIndexRoute: WorkIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
